#!/bin/bash

# use df command and look for the mounted USB drive
df_cmd=`df | grep JWST_UT16`
vol=${df_cmd##* }

if [[ -z "${vol// }" ]]; then
    echo "USB drive not found!"
    exit
fi

tarball="$vol/data/pandeia/pandeia.tgz"
cdbs="$vol/data/pandeia/cdbs.tgz"

echo "Unpacking $tarball in current directory..."
tar xvvzf $tarball
echo "Unpacking $cdbs in current directory..."
tar xvvzf $cdbs
export pandeia_refdata=`pwd`/pandeia_data
export PYSYN_CDBS=`pwd`/cdbs.23.1.rc3
cd pandeia/engine
python setup.py install
cd -
echo "Done."
echo "pandeia_refdata set to $pandeia_refdata."
echo "PYSYN_CDBS set to $PYSYN_CDBS."
