#!/bin/bash

# use df command and look for the mounted USB drive
df_cmd=`df | grep JWST_UT16`
vol=${df_cmd##* }

if [[ -z "${vol// }" ]]; then
    echo "USB drive not found!"
    exit
fi

tarball="$vol/data/tables/pandeia.tgz"

echo "Unpacking $tarball in current directory..."
tar xvvzf $tarball
export pandeia_refdata=`pwd`/pandeia_data
cd pandeia/engine
python setup.py install
cd -
echo "Done. pandeia_refdata set to $pandeia_refdata."
